// Standalone migration runner — runs the hand-rolled SQL files in ./drizzle
// directly against Neon over HTTPS. Replaces `drizzle-kit migrate` in CI.
//
// Why not drizzle-kit migrate?
// The CLI auto-picks @neondatabase/serverless and tries to open a WebSocket
// from a Node CLI context with no WebSocket polyfill — stalls in Vercel
// build, exits 1.
//
// Why not the drizzle-orm/neon-http/migrator?
// That migrator requires drizzle/meta/_journal.json, which only exists when
// migrations are generated by `drizzle-kit generate`. Our migrations are
// hand-rolled (every CREATE has IF NOT EXISTS, every ALTER has ADD COLUMN
// IF NOT EXISTS) — no journal exists, so the official migrator can't run.
//
// What this does:
// Reads every .sql file in ./drizzle, sorts by filename (which encodes order:
// 0000, 0001, 0002, …), splits each on `;`, executes each statement via the
// Neon HTTP client. Idempotent — safe to re-run on every deploy because
// every statement uses IF NOT EXISTS.
//
// Connection-string priority matches drizzle.config.ts: prefer NON-POOLED
// vars so DDL goes through a direct connection (Neon's pooler strips
// session features the migrator needs for transactional DDL).

import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import { sql } from "drizzle-orm";

const connectionString =
  process.env.DATABASE_URL_UNPOOLED ??       // Neon Native Vercel Integration
  process.env.POSTGRES_URL_NON_POOLING ??    // Legacy Vercel Postgres template name
  process.env.DATABASE_URL ??                // pooled — last-resort fallback
  process.env.POSTGRES_URL;                  // pooled — last-resort fallback

if (!connectionString) {
  console.error(
    "migrate: no Postgres connection string in env. " +
      "Expected one of: DATABASE_URL_UNPOOLED, POSTGRES_URL_NON_POOLING, " +
      "DATABASE_URL, POSTGRES_URL.",
  );
  process.exit(1);
}

const MIGRATIONS_DIR = "./drizzle";

async function main() {
  let files: string[];
  try {
    const all = await readdir(MIGRATIONS_DIR);
    files = all.filter((f) => f.endsWith(".sql")).sort();
  } catch (err) {
    console.error(`migrate: failed to read ${MIGRATIONS_DIR}`, err);
    process.exit(1);
  }

  if (files.length === 0) {
    console.log(`migrate: no .sql files found in ${MIGRATIONS_DIR} — nothing to do.`);
    return;
  }

  console.log(`migrate: found ${files.length} migration file(s):`);
  for (const f of files) console.log(`  - ${f}`);

  const client = neon(connectionString!);
  const db = drizzle(client);

  for (const file of files) {
    const path = join(MIGRATIONS_DIR, file);
    const content = await readFile(path, "utf8");

    // Strip `--` line comments BEFORE splitting on `;`. Comments can contain
    // semicolons (e.g. "Cookie holds an opaque random ID; the DB stores …"),
    // and naive split-on-semicolon would treat that as a statement break and
    // hand garbage to Postgres. Strip comments first, then split.
    const stripped = content
      .split("\n")
      .map((line) => {
        const idx = line.indexOf("--");
        return idx >= 0 ? line.slice(0, idx) : line;
      })
      .join("\n");

    const statements = stripped
      .split(";")
      .map((s) => s.trim())
      .filter((s) => s.length > 0);

    console.log(`migrate: applying ${file} (${statements.length} statement(s))`);

    for (const stmt of statements) {
      try {
        await db.execute(sql.raw(stmt));
      } catch (err) {
        const preview = stmt.replace(/\s+/g, " ").slice(0, 100);
        console.error(`migrate: ${file} failed at statement: ${preview}…`, err);
        process.exit(1);
      }
    }
  }

  console.log("migrate: done.");
}

main();
